spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/quiz
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
mail-sender:
    active: disable
    email: ${EMAIL_SENDER}
    password: ${EMAIL_PASSWORD}
