spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/quiz
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  config:
    activate:
      on-profile: "dev"
mail-sender:
  active: disable
  email: ${EMAIL_SENDER}
  password: ${EMAIL_PASSWORD}
jwt:
  secret: itquizsecrettokendev
server:
  port: 443
  ssl:
    key-store: src\main\resources\keystore.p12
    key-store-password: itquiz
    keyStoreType: PKCS12
    keyAlias: tomcat
security:
  require-ssl: true